// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhjp1FHRVB__wT3z9VPn2KC99dUgwrhp8',
    appId: '1:797775920538:web:81aca3808647917bfa0e23',
    messagingSenderId: '797775920538',
    projectId: 'blog-app-844ab',
    authDomain: 'blog-app-844ab.firebaseapp.com',
    storageBucket: 'blog-app-844ab.appspot.com',
    measurementId: 'G-244M4K45WJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcpiG6amJThtaGDHYTLktHLQPwLflPMN8',
    appId: '1:797775920538:android:1ce5028bbd0a6efafa0e23',
    messagingSenderId: '797775920538',
    projectId: 'blog-app-844ab',
    storageBucket: 'blog-app-844ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk2N5L3Ji9cVyA7yZby9aX_QgV0PECcEw',
    appId: '1:797775920538:ios:ed43677e1b96475afa0e23',
    messagingSenderId: '797775920538',
    projectId: 'blog-app-844ab',
    storageBucket: 'blog-app-844ab.appspot.com',
    iosClientId: '797775920538-d9pr0shae0429k3sn3l6ook1en8aiqls.apps.googleusercontent.com',
    iosBundleId: 'com.example.blogApp',
  );
}
